---
  #byxussof need to check
- name: Download docker-compose
  become: true
  become_user: root
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose

- name: Allowing executable
  become: true
  become_user: root
  file:
    path: /usr/local/bin/docker-compose
    mode: "u+x,g+x,o+x"
